### ISSUE TITLE
config.yml resetting on every reload

### ISSUE THREAD

**Issue by GamerMedic** [webbukkit/Dynmap-WorldGuard#73]
Every time I want to update the regions appearing on Dynmap the config.yml resets itself to the default setup after a server restart. Occasionally it will reformat the `hiddenregions` list to an improper YAML format or will reset it to the default empty array.

I set the hiddenregions list as ["region1", "region2"] etc. On reload it will either change to hiddenregions: [] or to the improper YAML format of

hiddenregions:
\- region1
\- region2

instead of

hiddenregions:
  \- region1
  \- region2

This causes the regions to not appear on Dynmap at all. Server restarts also cause the custstyle and infowindow configuration sections to reset to the default.

This whole experience makes the plugin completely useless, because either all regions appear (which makes for a messy map), or no regions appear at all (defeating the purpose of using the plugin).

Server version PurPur 1.19.2
Dynmap-WorldGuard version 1.2
Dynmap version 3.4-828

**Comment by JurgenKuyper** [comment]
```yml
update:
  # Seconds between checks for Residence updates
  period: 2
layer:
  name: WorldGuard
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 0
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
use3dregions: false
infowindow: <div class=\"infowindow\"><span style=\"font-size:120%;">%regionname%
  (%parent%) - %priority%</span><br /> Owners <span style="font-weight:bold;">%playerowners%<br/>%groupowners%</span><br/>Members
  <span style="font-weight:bold;">%playermembers%<br/>%groupmembers%</span><br/>Flags<br
  /><span style="font-weight:bold;">%flags%</span></div>
regionstyle:
  strokeColor: '#FF0000'
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: '#FF0000'
  fillOpacity: 0.35
  unownedStrokeColor: '#00FF00'
visibleregions: []
hiddenregions:
- world/test
custstyle:
  customregion1:
    strokeColor: '#00FF00'
  test:
    strokeColor: '#00FFFF'
  test2:
    strokeColor: '#FFFFFF'
ownerstyle:
  kingoftheworld:
    strokecolor: '#C0C0C0'
maxdepth: 16
updates-per-tick: 20
```
this config works for me, test and test2 are wg defined regions, and only test2 is showing, as is expected.
